### PR TITLE
Introduce Clippy

### PR DESCRIPTION
**Pull request by mfigurski80**
Solves Issue #16.

Hey @danielpclark. I don't know exactly what your CI looks like since it seems private, but I added a command that would reject builds if Clippy generates any warnings. Additionally, I fixed some of the issues it highlighted. 

In doing this, I wanted to rewrite some of the functions to utilize `iter` more because Clippy dislikes creating variables just to index things, but these tend to hurt performance. All except for one: `intersect_if` went from a bench of [802 ns/iter (+/- 26)] to [674 ns/iter (+/- 10)] with a few iterators. It's cool to have those benchmarks btw :+1: 

Let me know If this fits your config or if it's entirely useless for you

### CODE REVIEW

**Comment by mfigurski80** [comment]
Hey @danielpclark. Added a quick change to your Appveyor CI that should add Github notifications: i.e include that checkmark on commits and essentially bring the CI results closer to the package source.

In order to get it working for *this* repo, you'll have to generate your own GitHub auth token for the tool and then somehow encode it using the YAML tool AppVeyor gives you. You can see it working on my fork however if you want to inspect it.

Your input is welcome!

**Comment by danielpclark** [comment]
Hey!  Thanks for this.  I’ve had my hands full coaching recently and I should try and get this in Sunday.

**Comment by danielpclark** [comment]
Hey @mfigurski80 I spent 4 hours going through every small change running benchmarks with and without and I've found that these changes make bench test `subst_marks` 165ns slower, `times` 200ns slower, and `uniques1` 100ns slower.  And for your intersect changes it's within margin of error, slightly faster, but the side effects on the overall benches would rule it out.

As for clippy, because these methods are best left optimized for speed we won't be following clippy code quality rules as it will lead to slower results.  Thank you anyways for the effort you put in to this.

**Comment by mfigurski80** [comment]
Makes sense. Thanks for the thorough review!!

**Pull request closed without merging**
